#!/usr/bin/env node
"use strict";
// tools/mwb-edit.mjs — scripted maintenance for MySQL Workbench (.mwb) model files.
//
// A .mwb file is a ZIP archive containing:
//   document.mwb.xml  — the model (GRT-format XML: tables, columns, indexes,
//                         foreign keys, EER diagrams, figures, connections)
//   lock              — 6-byte open-lock marker (preserved byte-for-byte)
//   @db/data.db       — SQLite cache, regenerated by Workbench (omitted on write)
//
// All SQL/schema edits go through document.mwb.xml. Objects created or
// modified by this tool get struct-checksum="0x0" (Workbench accepts this and
// recomputes on save); untouched objects are preserved byte-for-byte in
// structure. New _ptr_ values are minted uniquely.
//
// Usage:
//   node tools/mwb-edit.mjs digest --mwb <file.mwb> [--json] [--out <file>]
//   node tools/mwb-edit.mjs apply --mwb <in.mwb> --spec <edits.json> --out <out.mwb> [--dry-run]
//   node tools/mwb-edit.mjs roundtrip --mwb <in.mwb> --out <out.mwb>
//   node tools/mwb-edit.mjs wbcheck --mwb <file.mwb> [--wb]
//
// Spec format (apply --spec), all keys optional:
// {
//   "renameTables":  [{"from": "A", "to": "B"}],
//   "renameColumns": [{"table": "T", "from": "a", "to": "b"}],
//   "createDiagrams": [{"name": "New Diagram"}],
//   "addTables": [{
//     "name": "T", "comment": "", "engine": "InnoDB",
//     "diagram": "Personal Data", "x": 100, "y": 100, "color": "#808080",
//     "columns": [
//       {"name": "id", "type": "BIGINT UNSIGNED", "notNull": true,
//        "autoIncrement": true, "pk": true, "comment": ""},
//       {"name": "label", "type": "VARCHAR(100)", "default": null},
//       {"name": "kind", "type": "ENUM('a','b')"},
//       {"name": "amount", "type": "DECIMAL(10,2)"}
//     ],
//     "primaryKey": ["id"],
//     "indexes": [{"name": "idx_t_label", "columns": ["label"], "unique": true}],
//     "foreignKeys": [{
//       "name": "fk_t_other", "columns": ["otherId"],
//       "refTable": "Other", "refColumns": ["id"],
//       "onDelete": "CASCADE", "onUpdate": "NO ACTION", "diagrams": ["Personal Data"]
//     }]
//   }],
//   "addColumns": [{"table": "T", "columns": [ ... ]}],
//   "placeTables": [{"table": "Existing", "diagram": "D", "x": 20, "y": 20}],
//   "addForeignKeys": [{"table": "T", "name": "...", "columns": [...],
//                       "refTable": "...", "refColumns": [...],
//                       "onDelete": "NO ACTION", "onUpdate": "NO ACTION",
//                       "diagrams": ["..."]}]
// }
// A "diagram" named in addTables that does not exist is created automatically.
// Foreign-key connections are drawn on every listed diagram (default: every
// diagram where both endpoint tables have figures).

import { readFileSync, writeFileSync, mkdtempSync, copyFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { inflateRawSync, deflateRawSync } from 'zlib';
import { randomUUID } from 'crypto';
import { spawnSync } from 'child_process';

const SCHEMA_NAME = 'IHRMIS';
const FK_RULES = ['NO ACTION', 'CASCADE', 'SET NULL', 'RESTRICT'];

// ---------------------------------------------------------------------------
// tiny CLI helpers
// ---------------------------------------------------------------------------

function parseArgs(argv) {
    const out = { _: [] };
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a.startsWith('--')) {
            const k = a.slice(2);
            if (i + 1 < argv.length && !argv[i + 1].startsWith('--')) {
                out[k] = argv[++i];
            } else {
                out[k] = true;
            }
        } else {
            out._.push(a);
        }
    }
    return out;
}

function fail(msg) {
    process.stderr.write(`mwb-edit: error: ${msg}\n`);
    process.exit(1);
}

function info(msg) {
    process.stderr.write(`mwb-edit: ${msg}\n`);
}

// ---------------------------------------------------------------------------
// crc32 (for ZIP headers)
// ---------------------------------------------------------------------------

const CRC_TABLE = (() => {
    const t = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
        let c = n;
        for (let k = 0; k < 8; k++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
        t[n] = c >>> 0;
    }
    return t;
})();

function crc32(buf) {
    let c = 0xffffffff;
    for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
}

function dosDateTime(d) {
    const time = ((d.getHours() & 31) << 11) | ((d.getMinutes() & 63) << 5) | ((Math.floor(d.getSeconds() / 2)) & 31);
    const date = (((d.getFullYear() - 1980) & 127) << 9) | (((d.getMonth() + 1) & 15) << 5) | (d.getDate() & 31);
    return { time, date };
}

function stampNow() {
    const d = new Date();
    const p = (n) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

// ---------------------------------------------------------------------------
// minimal ZIP reader/writer (stored + deflated entries)
// ---------------------------------------------------------------------------

function readZip(buf) {
    let eocd = -1;
    for (let i = buf.length - 22; i >= Math.max(0, buf.length - 65558); i--) {
        if (buf.readUInt32LE(i) === 0x06054b50) { eocd = i; break; }
    }
    if (eocd < 0) throw new Error('not a ZIP archive (EOCD not found)');
    const count = buf.readUInt16LE(eocd + 10);
    const cdOff = buf.readUInt32LE(eocd + 16);
    const commentLen = buf.readUInt16LE(eocd + 20);
    const comment = buf.slice(eocd + 22, eocd + 22 + commentLen);
    const entries = [];
    let p = cdOff;
    for (let i = 0; i < count; i++) {
        if (buf.readUInt32LE(p) !== 0x02014b50) throw new Error(`bad central directory at ${p}`);
        const method = buf.readUInt16LE(p + 10);
        const time = buf.readUInt16LE(p + 12);
        const date = buf.readUInt16LE(p + 14);
        const crc = buf.readUInt32LE(p + 16);
        const compSize = buf.readUInt32LE(p + 20);
        const uncompSize = buf.readUInt32LE(p + 24);
        const nameLen = buf.readUInt16LE(p + 28);
        const extraLen = buf.readUInt16LE(p + 30);
        const fileCommentLen = buf.readUInt16LE(p + 32);
        const extAttrs = buf.readUInt32LE(p + 38);
        const localOff = buf.readUInt32LE(p + 42);
        const name = buf.slice(p + 46, p + 46 + nameLen).toString('utf8');
        p += 46 + nameLen + extraLen + fileCommentLen;
        if (buf.readUInt32LE(localOff) !== 0x04034b50) throw new Error(`bad local header for ${name}`);
        // NOTE: entries may use data descriptors (flag bit 3); the central
        // directory holds the true sizes/CRC, which is what we rely on here.
        const lNameLen = buf.readUInt16LE(localOff + 26);
        const lExtraLen = buf.readUInt16LE(localOff + 28);
        const dataOff = localOff + 30 + lNameLen + lExtraLen;
        const raw = buf.slice(dataOff, dataOff + compSize);
        let data;
        if (method === 0) data = Buffer.from(raw);
        else if (method === 8) data = Buffer.from(inflateRawSync(raw));
        else throw new Error(`unsupported compression method ${method} (${name})`);
        if (data.length !== uncompSize) throw new Error(`size mismatch (${name})`);
        if (crc32(data) !== crc) throw new Error(`CRC mismatch (${name})`);
        entries.push({ name, method, time, date, attrs: extAttrs, data });
    }
    return { comment, entries };
}

function writeZip(entries, comment) {
    const chunks = [];
    const central = [];
    let offset = 0;
    for (const e of entries) {
        const nameBuf = Buffer.from(e.name, 'utf8');
        const raw = e.method === 8 ? deflateRawSync(e.data, { level: 9 }) : Buffer.from(e.data);
        const crc = crc32(e.data);
        const local = Buffer.alloc(30);
        local.writeUInt32LE(0x04034b50, 0);
        local.writeUInt16LE(20, 4);
        local.writeUInt16LE(0, 6);
        local.writeUInt16LE(e.method, 8);
        local.writeUInt16LE(e.time, 10);
        local.writeUInt16LE(e.date, 12);
        local.writeUInt32LE(crc, 14);
        local.writeUInt32LE(raw.length, 18);
        local.writeUInt32LE(e.data.length, 22);
        local.writeUInt16LE(nameBuf.length, 26);
        local.writeUInt16LE(0, 28);
        chunks.push(local, nameBuf, raw);
        central.push({ nameBuf, method: e.method, time: e.time, date: e.date, crc, comp: raw.length, uncomp: e.data.length, attrs: e.attrs, offset });
        offset += local.length + nameBuf.length + raw.length;
    }
    const cdStart = offset;
    const cdChunks = [];
    for (const c of central) {
        const h = Buffer.alloc(46);
        h.writeUInt32LE(0x02014b50, 0);
        h.writeUInt16LE(63, 4); // version made by (unix)
        h.writeUInt16LE(20, 6);
        h.writeUInt16LE(0, 8);
        h.writeUInt16LE(c.method, 10);
        h.writeUInt16LE(c.time, 12);
        h.writeUInt16LE(c.date, 14);
        h.writeUInt32LE(c.crc, 16);
        h.writeUInt32LE(c.comp, 20);
        h.writeUInt32LE(c.uncomp, 24);
        h.writeUInt16LE(c.nameBuf.length, 28);
        h.writeUInt16LE(0, 30);
        h.writeUInt16LE(0, 32);
        h.writeUInt16LE(0, 34);
        h.writeUInt16LE(0, 36);
        h.writeUInt32LE(c.attrs, 38);
        h.writeUInt32LE(c.offset, 42);
        cdChunks.push(h, c.nameBuf);
        offset += h.length + c.nameBuf.length;
    }
    const cdSize = offset - cdStart;
    const end = Buffer.alloc(22);
    end.writeUInt32LE(0x06054b50, 0);
    end.writeUInt16LE(0, 4);
    end.writeUInt16LE(0, 6);
    end.writeUInt16LE(central.length, 8);
    end.writeUInt16LE(central.length, 10);
    end.writeUInt32LE(cdSize, 12);
    end.writeUInt32LE(cdStart, 16);
    end.writeUInt16LE(comment.length, 20);
    return Buffer.concat([...chunks, ...cdChunks, end, comment]);
}

// ---------------------------------------------------------------------------
// minimal GRT-XML parser/serializer (elements: value, link, data)
// ---------------------------------------------------------------------------

const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'" };

function decodeEntities(s) {
    return s.replace(/&(#\d+|#x[0-9a-fA-F]+|[a-zA-Z]+);/g, (m, e) => {
        if (e[0] === '#') {
            const cp = e[1] === 'x' || e[1] === 'X' ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
            return String.fromCodePoint(cp);
        }
        if (e in ENTITIES) return ENTITIES[e];
        throw new Error(`unknown entity &${e};`);
    });
}

function parseXml(src) {
    let pos = 0;
    const failAt = (msg) => { throw new Error(`${msg} (offset ${pos})`); };

    let decl = '';
    if (src.startsWith('<?', pos)) {
        const end = src.indexOf('?>', pos);
        if (end < 0) failAt('unterminated processing instruction');
        decl = src.slice(pos, end + 2);
        pos = end + 2;
    }

    function skipWs() {
        while (pos < src.length && ' \t\r\n'.includes(src[pos])) pos++;
    }

    function readAttrs() {
        const attrs = [];
        for (;;) {
            skipWs();
            if (src.startsWith('/>', pos) || src[pos] === '>') break;
            const m = /^[A-Za-z_][\w:.-]*/.exec(src.slice(pos));
            if (!m) failAt('expected attribute name');
            const name = m[0];
            pos += name.length;
            skipWs();
            if (src[pos] !== '=') failAt(`expected = after ${name}`);
            pos++;
            skipWs();
            const q = src[pos];
            if (q !== '"' && q !== "'") failAt(`expected quote for ${name}`);
            pos++;
            const end = src.indexOf(q, pos);
            if (end < 0) failAt(`unterminated value for ${name}`);
            attrs.push([name, decodeEntities(src.slice(pos, end))]);
            pos = end + 1;
        }
        return attrs;
    }

    function readNode() {
        skipWs();
        if (!src.startsWith('<', pos)) failAt('expected <');
        if (src.startsWith('<!--', pos)) {
            const end = src.indexOf('-->', pos + 4);
            if (end < 0) failAt('unterminated comment');
            pos = end + 3;
            return readNode();
        }
        if (src.startsWith('<![CDATA[', pos)) failAt('CDATA not supported');
        if (src[pos + 1] === '?' || src[pos + 1] === '!') failAt('unexpected markup');
        if (src[pos + 1] === '/') failAt('unexpected closing tag');
        const m = /^<([A-Za-z][\w:.-]*)/.exec(src.slice(pos));
        if (!m) failAt('expected tag name');
        const tag = m[1];
        pos += m[0].length;
        const attrs = readAttrs();
        if (src.startsWith('/>', pos)) {
            pos += 2;
            return { tag, attrs, kids: [], text: '' };
        }
        if (src[pos] !== '>') failAt('expected >');
        pos++;
        const kids = [];
        let text = '';
        for (;;) {
            if (src.startsWith('</', pos)) {
                const cm = /^<\/([A-Za-z][\w:.-]*)\s*>/.exec(src.slice(pos));
                if (!cm) failAt('bad closing tag');
                if (cm[1] !== tag) failAt(`mismatched close tag </${cm[1]}> for <${tag}>`);
                pos += cm[0].length;
                break;
            }
            if (src[pos] === '<') {
                if (src.startsWith('<!--', pos)) {
                    const end = src.indexOf('-->', pos + 4);
                    if (end < 0) failAt('unterminated comment');
                    pos = end + 3;
                    continue;
                }
                if (src.startsWith('<![CDATA[', pos)) failAt('CDATA not supported');
                kids.push(readNode());
                continue;
            }
            const next = src.indexOf('<', pos);
            if (next < 0) failAt('unterminated text');
            const chunk = src.slice(pos, next);
            pos = next;
            if (chunk.trim() !== '') {
                if (kids.length) failAt(`mixed content in <${tag}>`);
                text += decodeEntities(chunk);
            }
        }
        return { tag, attrs, kids, text };
    }

    skipWs();
    const root = readNode();
    skipWs();
    if (pos !== src.length) failAt('trailing content');
    return { decl, root };
}

function escText(s) {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escAttr(s) {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function serializeXml(decl, root) {
    const lines = [decl];
    function emit(node, depth) {
        const pad = '  '.repeat(depth);
        const a = node.attrs.map(([k, v]) => ` ${k}="${escAttr(v)}"`).join('');
        if (!node.kids.length && !node.text) {
            lines.push(`${pad}<${node.tag}${a}/>`);
        } else if (!node.kids.length) {
            lines.push(`${pad}<${node.tag}${a}>${escText(node.text)}</${node.tag}>`);
        } else {
            lines.push(`${pad}<${node.tag}${a}>`);
            for (const k of node.kids) emit(k, depth + 1);
            lines.push(`${pad}</${node.tag}>`);
        }
    }
    emit(root, 0);
    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// GRT DOM helpers
// ---------------------------------------------------------------------------

function attr(node, name) {
    const f = node.attrs.find(([k]) => k === name);
    return f ? f[1] : undefined;
}

function setAttr(node, name, value) {
    const f = node.attrs.find(([k]) => k === name);
    if (f) f[1] = value;
    else node.attrs.push([name, value]);
}

function val(type, attrs, text = '', kids = []) {
    return { tag: 'value', attrs: [['type', type], ...attrs], kids, text };
}

function lnk(structName, key, target) {
    const attrs = [['type', 'object']];
    if (structName) attrs.push(['struct-name', structName]);
    if (key) attrs.push(['key', key]);
    return { tag: 'link', attrs, kids: [], text: target };
}

function child(node, key) {
    return node.kids.find((k) => attr(k, 'key') === key);
}

function children(node, key) {
    const c = child(node, key);
    return c ? c.kids : [];
}

function childText(node, key) {
    const c = child(node, key);
    return c ? c.text : undefined;
}

function isExternalRef(text) {
    return !/^\{[^}]*\}$/.test(text || '');
}

function newId() {
    return `{${randomUUID().toUpperCase()}}`;
}

class PtrMint {
    constructor(root) {
        this.used = new Set();
        const walk = (n) => {
            const p = attr(n, '_ptr_');
            if (p) this.used.add(p);
            for (const k of n.kids) walk(k);
        };
        walk(root);
        this.next = 0x100000;
    }
    mint() {
        let v;
        do {
            v = '0x' + (this.next++).toString(16).padStart(12, '0');
        } while (this.used.has(v));
        this.used.add(v);
        return v;
    }
}

function touch(node) {
    if (node.tag === 'value' && node.attrs.some(([k]) => k === 'struct-checksum')) {
        setAttr(node, 'struct-checksum', '0x0');
    }
}

function idMap(root) {
    const map = new Map();
    const walk = (n) => {
        const id = attr(n, 'id');
        if (id) {
            if (map.has(id)) throw new Error(`duplicate id ${id}`);
            map.set(id, n);
        }
        for (const k of n.kids) walk(k);
    };
    walk(root);
    return map;
}

function findSchema(root) {
    for (const n of walkAll(root)) {
        if (n.tag === 'value' && attr(n, 'type') === 'object' && attr(n, 'struct-name') === 'db.mysql.Schema') {
            if (childText(n, 'name') === SCHEMA_NAME) return n;
        }
    }
    for (const n of walkAll(root)) {
        if (n.tag === 'value' && attr(n, 'type') === 'object' && attr(n, 'struct-name') === 'db.mysql.Schema') return n;
    }
    throw new Error('no db.mysql.Schema found in model');
}

function *walkAll(root) {
    yield root;
    for (const k of root.kids) yield* walkAll(k);
}

function findPhysicalModel(root) {
    for (const n of walkAll(root)) {
        if (n.tag === 'value' && attr(n, 'type') === 'object' && attr(n, 'struct-name') === 'workbench.physical.Model') return n;
    }
    throw new Error('no workbench.physical.Model found in model');
}

function diagramsOf(physModel) {
    return children(physModel, 'diagrams');
}

function diagramByName(physModel, name) {
    return diagramsOf(physModel).find((d) => childText(d, 'name') === name);
}

function tablesOf(schema) {
    return children(schema, 'tables');
}

function tableByName(schema, name) {
    return tablesOf(schema).find((t) => childText(t, 'name') === name);
}

function colsOf(table) {
    return children(table, 'columns');
}

function colByName(table, name) {
    return colsOf(table).find((c) => childText(c, 'name') === name);
}

function idxByName(table, name) {
    return children(table, 'indices').find((i) => childText(i, 'name') === name);
}

function figuresOf(diagram) {
    return children(diagram, 'figures');
}

function figureForTable(diagram, tableId) {
    return figuresOf(diagram).find((f) => {
        const t = child(f, 'table');
        return t && t.text === tableId;
    });
}

// ---------------------------------------------------------------------------
// SQL type handling
// ---------------------------------------------------------------------------

const GRT_TYPES = new Set([
    'bigint', 'int', 'smallint', 'mediumint', 'tinyint', 'bit', 'boolean',
    'decimal', 'float', 'double', 'real',
    'char', 'nchar', 'varchar', 'nvarchar', 'binary', 'varbinary',
    'tinytext', 'text', 'mediumtext', 'longtext',
    'tinyblob', 'blob', 'mediumblob', 'longblob',
    'date', 'datetime', 'datetime_f', 'timestamp', 'timestamp_f', 'time', 'year',
    'enum', 'set', 'json',
    'point', 'linestring', 'polygon', 'multipoint', 'multilinestring',
    'multipolygon', 'geometrycollection', 'geometry',
]);

const SQL_ALIASES = {
    integer: 'int', bool: 'boolean', numeric: 'decimal', dec: 'decimal',
    'double precision': 'double', character: 'char', nchar: 'nchar',
};

function parseType(spec, colName) {
    // returns {grt, length, precision, scale, values, unsigned}
    let typeStr, unsigned = false;
    if (typeof spec === 'string') {
        typeStr = spec.trim();
    } else {
        typeStr = String(spec.type || '').trim();
        unsigned = !!spec.unsigned;
    }
    const m = /^([A-Z][A-Z ]*?)(?:\s*\(\s*([^)]*?)\s*\))?(?:\s+(UNSIGNED))?\s*$/i.exec(typeStr);
    if (!m) fail(`cannot parse column type "${typeStr}" (column ${colName})`);
    let base = m[1].trim().toLowerCase().replace(/\s+/, ' ');
    const params = (m[2] || '').trim();
    if (m[3]) unsigned = true;
    if (SQL_ALIASES[base]) base = SQL_ALIASES[base];
    let grt = base, length = -1, precision = -1, scale = -1, values = null;
    const needLen = new Set(['char', 'nchar', 'varchar', 'nvarchar', 'binary', 'varbinary']);
    if (base === 'decimal') {
        if (params) {
            const ps = params.split(',').map((s) => parseInt(s.trim(), 10));
            precision = ps[0]; scale = ps.length > 1 ? ps[1] : 0;
            if (!Number.isInteger(precision)) fail(`bad DECIMAL params "${params}" (column ${colName})`);
        } else { precision = 10; scale = 0; }
    } else if (base === 'datetime' || base === 'timestamp') {
        const fsp = params ? parseInt(params, 10) : 0;
        if (params && !Number.isInteger(fsp)) fail(`bad fsp "${params}" (column ${colName})`);
        if (fsp > 0) grt = base + '_f';
    } else if (base === 'enum' || base === 'set') {
        values = splitEnumParams(params, colName);
    } else if (needLen.has(base)) {
        length = parseInt(params, 10);
        if (!Number.isInteger(length)) fail(`type ${base.toUpperCase()} requires a length (column ${colName})`);
    } else if (params && base !== 'float' && base !== 'double' && base !== 'real') {
        fail(`type ${base.toUpperCase()} takes no parameters (column ${colName})`);
    }
    if (!GRT_TYPES.has(grt)) fail(`unsupported column type "${typeStr}" (column ${colName})`);
    return { grt, length, precision, scale, values, unsigned };
}

function splitEnumParams(params, colName) {
    if (!params) fail(`ENUM/SET requires a value list (column ${colName})`);
    const out = [];
    const re = /'((?:[^']|'')*)'\s*(?:,|$)/g;
    let m, consumed = '';
    while ((m = re.exec(params)) !== null) {
        out.push(m[1].replace(/''/g, "'"));
        consumed = params.slice(0, re.lastIndex);
    }
    if (!out.length || consumed.trim().replace(/,+$/, '') !== params.trim().replace(/,+$/, '')) {
        // fallback: bare comma split
        const bare = params.split(',').map((s) => s.trim()).filter(Boolean);
        if (!bare.length) fail(`bad ENUM/SET value list "${params}" (column ${colName})`);
        return bare;
    }
    return out;
}

function displayType(col) {
    const st = childText(col, 'simpleType') || '';
    const base = st.split('.').pop().toUpperCase();
    const len = childText(col, 'length');
    const prec = childText(col, 'precision');
    const scale = childText(col, 'scale');
    const flags = children(col, 'flags').map((f) => f.text).join(' ');
    let s = base;
    if (base === 'DECIMAL') s += `(${prec},${scale})`;
    else if (['VARCHAR', 'CHAR', 'NVARCHAR', 'NCHAR', 'BINARY', 'VARBINARY'].includes(base)) s += `(${len})`;
    else if (base === 'ENUM' || base === 'SET') s += `(${childText(col, 'datatypeExplicitParams')})`;
    if (flags) s += ' ' + flags;
    return s;
}

// ---------------------------------------------------------------------------
// builders (mirror structures observed in DB-ERD.mwb)
// ---------------------------------------------------------------------------

function emptyList(mint, structName) {
    return { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', structName]], kids: [], text: '' };
}

function emptyDict(mint) {
    return { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'dict']], kids: [], text: '' };
}

function buildColumn(mint, spec, tableId) {
    const t = parseType(spec.type || spec, spec.name);
    const isPk = !!spec.pk;
    const notNull = isPk || !!spec.notNull;
    const autoInc = !!spec.autoIncrement;
    const flags = t.unsigned ? [{ tag: 'value', attrs: [['type', 'string']], kids: [], text: 'UNSIGNED' }] : [];
    const hasDefault = spec.default !== undefined && spec.default !== null;
    const colId = newId();
    const col = {
        tag: 'value',
        attrs: [['type', 'object'], ['struct-name', 'db.mysql.Column'], ['id', colId], ['struct-checksum', '0x0']],
        kids: [
            val('int', [['key', 'autoIncrement']], autoInc ? '1' : '0'),
            val('string', [['key', 'expression']]),
            val('int', [['key', 'generated']], spec.generated ? '1' : '0'),
            val('string', [['key', 'generatedStorage']], spec.generated ? 'VIRTUAL' : (autoInc ? 'VIRTUAL' : '')),
            val('string', [['key', 'characterSetName']]),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'db.CheckConstraint'], ['key', 'checks']], kids: [], text: '' },
            val('string', [['key', 'collationName']]),
            val('string', [['key', 'datatypeExplicitParams']], t.values ? `(${t.values.map((v) => `'${v.replace(/'/g, "''")}'`).join(',')})` : ''),
            val('string', [['key', 'defaultValue']], hasDefault ? String(spec.default) : ''),
            val('int', [['key', 'defaultValueIsNull']], hasDefault ? '0' : (spec.default === null && !notNull ? '1' : '0')),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'string'], ['key', 'flags']], kids: flags, text: '' },
            val('int', [['key', 'isNotNull']], notNull ? '1' : '0'),
            val('int', [['key', 'length']], String(t.length)),
            val('int', [['key', 'precision']], String(t.precision)),
            val('int', [['key', 'scale']], String(t.scale)),
            lnk('db.SimpleDatatype', 'simpleType', `com.mysql.rdbms.mysql.datatype.${t.grt}`),
            val('string', [['key', 'comment']], spec.comment || ''),
            val('string', [['key', 'name']], spec.name),
            val('string', [['key', 'oldName']], spec.name),
            lnk('GrtObject', 'owner', tableId),
        ],
        text: '',
    };
    return col;
}

function buildIndex(mint, { name, oldName, columnIds, tableId, kind }) {
    // kind: 'PRIMARY' | 'INDEX'
    const idxId = newId();
    const isPrimary = kind === 'PRIMARY';
    const cols = columnIds.map((cid) => ({
        tag: 'value',
        attrs: [['type', 'object'], ['struct-name', 'db.mysql.IndexColumn'], ['id', newId()], ['struct-checksum', '0x0']],
        kids: [
            val('int', [['key', 'columnLength']], '0'),
            val('string', [['key', 'comment']]),
            val('int', [['key', 'descend']], '0'),
            val('string', [['key', 'expression']]),
            lnk('db.Column', 'referencedColumn', cid),
            val('string', [['key', 'name']]),
            lnk('GrtObject', 'owner', idxId),
        ],
        text: '',
    }));
    return {
        tag: 'value',
        attrs: [['type', 'object'], ['struct-name', 'db.mysql.Index'], ['id', idxId], ['struct-checksum', '0x0']],
        kids: [
            val('string', [['key', 'algorithm']]),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'db.mysql.IndexColumn'], ['key', 'columns']], kids: cols, text: '' },
            val('string', [['key', 'indexKind']]),
            val('int', [['key', 'keyBlockSize']], '0'),
            val('string', [['key', 'lockOption']]),
            val('int', [['key', 'visible']], '1'),
            val('string', [['key', 'withParser']]),
            val('string', [['key', 'comment']]),
            val('int', [['key', 'deferability']], '0'),
            val('string', [['key', 'indexType']], kind),
            val('int', [['key', 'isPrimary']], isPrimary ? '1' : '0'),
            val('string', [['key', 'name']], name),
            val('int', [['key', 'unique']], '0'),
            val('int', [['key', 'commentedOut']], '0'),
            val('string', [['key', 'createDate']]),
            emptyDict(mint),
            val('string', [['key', 'lastChangeDate']]),
            val('int', [['key', 'modelOnly']], '0'),
            lnk('GrtNamedObject', 'owner', tableId),
            val('string', [['key', 'temp_sql']]),
            val('string', [['key', 'oldName']], oldName),
        ],
        text: '',
    };
}

function tableScalars(engine, comment, name, ownerId, now) {
    return [
        val('string', [['key', 'avgRowLength']]),
        val('int', [['key', 'checksum']], '0'),
        val('string', [['key', 'connectionString']]),
        val('string', [['key', 'defaultCharacterSetName']]),
        val('string', [['key', 'defaultCollationName']]),
        val('int', [['key', 'delayKeyWrite']], '0'),
    ];
}

function buildTable(mint, spec, schemaId) {
    const tableId = newId();
    const now = stampNow();
    const colNodes = (spec.columns || []).map((c) => buildColumn(mint, c, tableId));
    const colByName = new Map(colNodes.map((c) => [childText(c, 'name'), c]));
    // explicit primaryKey list wins; otherwise honour per-column pk flags
    const pk = spec.primaryKey || (spec.columns || []).filter((c) => c.pk).map((c) => c.name);
    if (!pk.length) fail(`table ${spec.name}: no primary key (set pk:true on a column or give primaryKey)`);
    const missingPk = pk.filter((n) => !colByName.has(n));
    if (missingPk.length) fail(`table ${spec.name}: primaryKey column(s) not defined: ${missingPk.join(', ')}`);
    const pkIdx = buildIndex(mint, {
        name: 'PRIMARY', oldName: 'PRIMARY',
        columnIds: pk.map((n) => attr(colByName.get(n), 'id')),
        tableId, kind: 'PRIMARY',
    });
    const indices = [pkIdx];
    for (const ix of spec.indexes || []) {
        const cids = (ix.columns || []).map((n) => {
            if (!colByName.has(n)) fail(`table ${spec.name}: index ${ix.name} references unknown column ${n}`);
            return attr(colByName.get(n), 'id');
        });
        const ixName = ix.name || `${spec.name}_${(ix.columns || []).join('_')}_idx`;
        const node = buildIndex(mint, { name: ixName, oldName: ixName, columnIds: cids, tableId, kind: 'INDEX' });
        if (ix.unique) {
            const u = child(node, 'unique');
            u.text = '1';
        }
        if (ix.comment) child(node, 'comment').text = ix.comment;
        indices.push(node);
    }
    const kids = [
        ...tableScalars(),
        { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'db.mysql.Column'], ['key', 'columns']], kids: colNodes, text: '' },
        val('string', [['key', 'connectionString']]),
        val('string', [['key', 'defaultCharacterSetName']]),
        val('string', [['key', 'defaultCollationName']]),
        val('int', [['key', 'delayKeyWrite']], '0'),
        { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'db.mysql.ForeignKey'], ['key', 'foreignKeys']], kids: [], text: '' },
        { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'db.mysql.Index'], ['key', 'indices']], kids: indices, text: '' },
        val('string', [['key', 'keyBlockSize']]),
        val('string', [['key', 'maxRows']]),
        val('string', [['key', 'mergeInsert']]),
        val('string', [['key', 'mergeUnion']]),
        val('string', [['key', 'minRows']]),
        val('string', [['key', 'nextAutoInc']]),
        val('string', [['key', 'packKeys']]),
        val('int', [['key', 'partitionCount']], '0'),
        { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'db.mysql.PartitionDefinition'], ['key', 'partitionDefinitions']], kids: [], text: '' },
        val('string', [['key', 'partitionExpression']]),
        val('int', [['key', 'partitionKeyAlgorithm']], '0'),
        val('string', [['key', 'partitionType']]),
        val('string', [['key', 'password']]),
        lnk('db.mysql.Index', 'primaryKey', attr(pkIdx, 'id')),
        val('string', [['key', 'raidChunkSize']]),
        val('string', [['key', 'raidChunks']]),
        val('string', [['key', 'raidType']]),
        val('string', [['key', 'rowFormat']]),
        val('string', [['key', 'statsAutoRecalc']]),
        val('string', [['key', 'statsPersistent']]),
        val('int', [['key', 'statsSamplePages']], '0'),
        val('int', [['key', 'subpartitionCount']], '0'),
        val('string', [['key', 'subpartitionExpression']]),
        val('int', [['key', 'subpartitionKeyAlgorithm']], '0'),
        val('string', [['key', 'subpartitionType']]),
        val('string', [['key', 'tableDataDir']]),
        val('string', [['key', 'tableEngine']], spec.engine || 'InnoDB'),
        val('string', [['key', 'tableIndexDir']]),
        val('string', [['key', 'tableSpace']]),
        { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'db.mysql.Trigger'], ['key', 'triggers']], kids: [], text: '' },
        val('int', [['key', 'isStub']], '0'),
        val('int', [['key', 'isSystem']], '0'),
        val('int', [['key', 'isTemporary']], '0'),
        val('string', [['key', 'temporaryScope']]),
        val('int', [['key', 'commentedOut']], '0'),
        val('string', [['key', 'createDate']], now),
        emptyDict(mint),
        val('string', [['key', 'lastChangeDate']], now),
        val('int', [['key', 'modelOnly']], '0'),
        val('string', [['key', 'name']], spec.name),
        lnk('GrtNamedObject', 'owner', schemaId),
        val('string', [['key', 'temp_sql']]),
        val('string', [['key', 'comment']], spec.comment || ''),
        val('string', [['key', 'oldName']]),
    ];
    // fix customData key (emptyDict has no key)
    kids.find((k) => k.tag === 'value' && attr(k, 'type') === 'dict').attrs.push(['key', 'customData']);
    return {
        tag: 'value',
        attrs: [['type', 'object'], ['struct-name', 'db.mysql.Table'], ['id', tableId], ['struct-checksum', '0x0']],
        kids, text: '',
    };
}

function buildForeignKey(mint, { name, tableId, columnIds, refTableId, refColumnIds, onDelete, onUpdate }) {
    const idxNode = buildIndex(mint, { name: `${name}_idx`, oldName: name, columnIds, tableId, kind: 'INDEX' });
    const fkId = newId();
    const fk = {
        tag: 'value',
        attrs: [['type', 'object'], ['struct-name', 'db.mysql.ForeignKey'], ['id', fkId], ['struct-checksum', '0x0']],
        kids: [
            lnk('db.mysql.Table', 'referencedTable', refTableId),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'db.Column'], ['key', 'columns']], kids: columnIds.map((id) => lnk(null, null, id)), text: '' },
            emptyDict(mint),
            val('int', [['key', 'deferability']], '0'),
            val('string', [['key', 'deleteRule']], onDelete),
            lnk('db.Index', 'index', attr(idxNode, 'id')),
            val('int', [['key', 'mandatory']], '1'),
            val('int', [['key', 'many']], '1'),
            val('int', [['key', 'modelOnly']], '0'),
            lnk('db.Table', 'owner', tableId),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'db.Column'], ['key', 'referencedColumns']], kids: refColumnIds.map((id) => lnk(null, null, id)), text: '' },
            val('int', [['key', 'referencedMandatory']], '1'),
            val('string', [['key', 'updateRule']], onUpdate),
            val('string', [['key', 'comment']]),
            val('string', [['key', 'name']], name),
            val('string', [['key', 'oldName']], name),
        ],
        text: '',
    };
    fk.kids.find((k) => k.tag === 'value' && attr(k, 'type') === 'dict').attrs.push(['key', 'customData']);
    return { fk, idxNode };
}

function buildFigure(mint, { tableId, tableName, layerId, diagramId, x, y, color }) {
    return {
        tag: 'value',
        attrs: [['type', 'object'], ['struct-name', 'workbench.physical.TableFigure'], ['id', newId()], ['struct-checksum', '0x0']],
        kids: [
            val('int', [['key', 'columnsExpanded']], '1'),
            val('int', [['key', 'foreignKeysExpanded']], '0'),
            val('int', [['key', 'indicesExpanded']], '0'),
            val('int', [['key', 'summarizeDisplay']], '-1'),
            lnk('db.Table', 'table', tableId),
            val('int', [['key', 'triggersExpanded']], '0'),
            val('string', [['key', 'color']], color || '#808080'),
            val('int', [['key', 'expanded']], '1'),
            val('real', [['key', 'height']], '145'),
            lnk('model.Layer', 'layer', layerId),
            val('real', [['key', 'left']], String(x)),
            val('int', [['key', 'locked']], '0'),
            val('int', [['key', 'manualSizing']], '0'),
            val('real', [['key', 'top']], String(y)),
            val('real', [['key', 'width']], '123'),
            lnk('model.Diagram', 'owner', diagramId),
            val('int', [['key', 'visible']], '1'),
            val('string', [['key', 'name']], tableName),
        ],
        text: '',
    };
}

function buildConnection(mint, { fkId, fkName, startFigureId, endFigureId, diagramId }) {
    return {
        tag: 'value',
        attrs: [['type', 'object'], ['struct-name', 'workbench.physical.Connection'], ['id', newId()], ['struct-checksum', '0x0']],
        kids: [
            val('string', [['key', 'caption']], fkName),
            val('real', [['key', 'captionXOffs']], '0'),
            val('real', [['key', 'captionYOffs']], '0'),
            val('string', [['key', 'comment']]),
            val('real', [['key', 'endCaptionXOffs']], '0'),
            val('real', [['key', 'endCaptionYOffs']], '0'),
            val('string', [['key', 'extraCaption']]),
            val('real', [['key', 'extraCaptionXOffs']], '0'),
            val('real', [['key', 'extraCaptionYOffs']], '0'),
            lnk('db.ForeignKey', 'foreignKey', fkId),
            val('real', [['key', 'middleSegmentOffset']], '0'),
            val('real', [['key', 'startCaptionXOffs']], '0'),
            val('real', [['key', 'startCaptionYOffs']], '0'),
            val('int', [['key', 'drawSplit']], '0'),
            lnk('model.Figure', 'endFigure', endFigureId),
            lnk('model.Figure', 'startFigure', startFigureId),
            lnk('model.Diagram', 'owner', diagramId),
            val('int', [['key', 'visible']], '1'),
            val('string', [['key', 'name']]),
        ],
        text: '',
    };
}

function buildDiagram(mint, name, physModelId) {
    const diagramId = newId();
    const layerId = newId();
    const layer = {
        tag: 'value',
        attrs: [['type', 'object'], ['struct-name', 'workbench.physical.Layer'], ['id', layerId], ['struct-checksum', '0x0'], ['key', 'rootLayer']],
        kids: [
            val('string', [['key', 'color']]),
            val('string', [['key', 'description']]),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'model.Figure'], ['key', 'figures']], kids: [], text: '' },
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'model.Layer'], ['key', 'groups']], kids: [], text: '' },
            val('real', [['key', 'height']], '986'),
            val('real', [['key', 'left']], '0'),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'model.Layer'], ['key', 'subLayers']], kids: [], text: '' },
            val('real', [['key', 'top']], '0'),
            val('real', [['key', 'width']], '2761.9'),
            lnk('model.Diagram', 'owner', diagramId),
            val('int', [['key', 'visible']], '1'),
            val('string', [['key', 'name']]),
        ],
        text: '',
    };
    const diagram = {
        tag: 'value',
        attrs: [['type', 'object'], ['struct-name', 'workbench.physical.Diagram'], ['id', diagramId], ['struct-checksum', '0x0']],
        kids: [
            val('int', [['key', 'closed']], '0'),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'model.Connection'], ['key', 'connections']], kids: [], text: '' },
            val('string', [['key', 'description']]),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'model.Figure'], ['key', 'figures']], kids: [], text: '' },
            val('real', [['key', 'height']], '986'),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'workbench.physical.Layer'], ['key', 'layers']], kids: [], text: '' },
            val('string', [['key', 'name']], name),
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'dict'], ['key', 'options']], kids: [], text: '' },
            lnk('workbench.physical.Model', 'owner', physModelId),
            layer,
            { tag: 'value', attrs: [['_ptr_', mint.mint()], ['type', 'list'], ['content-type', 'object'], ['content-struct-name', 'model.Marker'], ['key', 'selection']], kids: [], text: '' },
            val('int', [['key', 'updateBlocked']], '0'),
            val('real', [['key', 'width']], '2761.9'),
            val('real', [['key', 'x']], '0'),
            val('real', [['key', 'y']], '0'),
            val('real', [['key', 'zoom']], '1'),
        ],
        text: '',
    };
    return { diagram, layer };
}

// ---------------------------------------------------------------------------
// edit operations
// ---------------------------------------------------------------------------

function ensureDiagram(ctx, name, createdLog) {
    let d = diagramByName(ctx.physModel, name);
    if (d) return { diagram: d, created: false };
    const { diagram, layer } = buildDiagram(ctx.mint, name, attr(ctx.physModel, 'id'));
    child(ctx.physModel, 'diagrams').kids.push(diagram);
    createdLog.push(name);
    return { diagram, layer, created: true };
}

function layerOf(diagram) {
    const rl = child(diagram, 'rootLayer');
    if (!rl) fail(`diagram ${childText(diagram, 'name')}: no rootLayer`);
    return rl;
}

function autoPosition(diagram) {
    let maxRight = 0, maxBottom = 0;
    for (const f of figuresOf(diagram)) {
        const l = parseFloat(childText(f, 'left') || '0');
        const t = parseFloat(childText(f, 'top') || '0');
        const w = parseFloat(childText(f, 'width') || '123');
        const h = parseFloat(childText(f, 'height') || '145');
        maxRight = Math.max(maxRight, l + w);
        maxBottom = Math.max(maxBottom, t + h);
    }
    let x = maxRight ? maxRight + 60 : 20;
    let y = 20;
    const W = parseFloat(childText(diagram, 'width') || '2761.9');
    if (x + 200 > W) { x = 20; y = maxBottom + 40; }
    return { x: Math.round(x), y: Math.round(y) };
}

function placeFigure(ctx, diagram, tableNode, spec, log) {
    const tableId = attr(tableNode, 'id');
    const tableName = childText(tableNode, 'name');
    if (figureForTable(diagram, tableId)) {
        log.push(`figure for ${tableName} already on ${childText(diagram, 'name')}`);
        return figureForTable(diagram, tableId);
    }
    const layer = layerOf(diagram);
    const pos = (spec.x !== undefined && spec.y !== undefined)
        ? { x: spec.x, y: spec.y }
        : autoPosition(diagram);
    const fig = buildFigure(ctx.mint, {
        tableId, tableName,
        layerId: attr(layer, 'id'),
        diagramId: attr(diagram, 'id'),
        x: pos.x, y: pos.y, color: spec.color,
    });
    child(diagram, 'figures').kids.push(fig);
    child(layer, 'figures').kids.push(lnk(null, null, attr(fig, 'id')));
    log.push(`placed ${tableName} on ${childText(diagram, 'name')} at (${pos.x}, ${pos.y})`);
    return fig;
}

function resolveColumns(tableNode, names, what) {
    return names.map((n) => {
        const c = colByName(tableNode, n);
        if (!c) fail(`${what}: column ${n} not found in table ${childText(tableNode, 'name')}`);
        return c;
    });
}

function addForeignKeyOp(ctx, ownerTable, spec, log) {
    const ownerName = childText(ownerTable, 'name');
    const refTable = tableByName(ctx.schema, spec.refTable);
    if (!refTable) fail(`foreign key ${spec.name}: referenced table ${spec.refTable} not found`);
    const cols = resolveColumns(ownerTable, spec.columns || [], `foreign key ${spec.name}`);
    const refCols = resolveColumns(refTable, spec.refColumns || [], `foreign key ${spec.name}`);
    if (cols.length !== refCols.length || !cols.length) {
        fail(`foreign key ${spec.name}: columns/refColumns must be non-empty and equal length`);
    }
    // type-compatibility warning
    cols.forEach((c, i) => {
        const a = displayType(c), b = displayType(refCols[i]);
        const ta = (childText(c, 'simpleType') || '').split('.').pop();
        const tb = (childText(refCols[i], 'simpleType') || '').split('.').pop();
        if (ta !== tb) log.push(`warning: ${spec.name} type mismatch ${a} -> ${b}`);
    });
    for (const rule of [spec.onDelete || 'NO ACTION', spec.onUpdate || 'NO ACTION']) {
        if (!FK_RULES.includes(rule)) fail(`foreign key ${spec.name}: bad rule "${rule}" (use ${FK_RULES.join('|')})`);
    }
    const { fk, idxNode } = buildForeignKey(ctx.mint, {
        name: spec.name,
        tableId: attr(ownerTable, 'id'),
        columnIds: cols.map((c) => attr(c, 'id')),
        refTableId: attr(refTable, 'id'),
        refColumnIds: refCols.map((c) => attr(c, 'id')),
        onDelete: spec.onDelete || 'NO ACTION',
        onUpdate: spec.onUpdate || 'NO ACTION',
    });
    child(ownerTable, 'foreignKeys').kids.push(fk);
    const existing = idxByName(ownerTable, `${spec.name}_idx`);
    if (existing) {
        const link = child(fk, 'index');
        if (link) link.text = attr(existing, 'id');
        log.push(`note: ${spec.name} reuses existing index ${childText(existing, 'name')} as backing`);
    } else {
        child(ownerTable, 'indices').kids.push(idxNode);
    }
    touch(ownerTable);
    log.push(`added foreign key ${spec.name} on ${ownerName} -> ${spec.refTable}`);
    // connections are drawn in a deferred pass (drawPendingConnections) so
    // that figures placed later in the same spec are already present.
    ctx.pending.push({
        fkId: attr(fk, 'id'), fkName: spec.name,
        ownerTableId: attr(ownerTable, 'id'), refTableId: attr(refTable, 'id'),
        diagrams: spec.diagrams || null,
    });
}

function drawPendingConnections(ctx, log) {
    for (const p of ctx.pending) {
        let diagrams;
        if (p.diagrams) {
            diagrams = p.diagrams.map((n) => {
                const d = diagramByName(ctx.physModel, n);
                if (!d) fail(`foreign key ${p.fkName}: diagram ${n} not found`);
                return d;
            });
        } else {
            diagrams = diagramsOf(ctx.physModel).filter((d) =>
                figureForTable(d, p.ownerTableId) && figureForTable(d, p.refTableId));
        }
        let drew = 0;
        for (const d of diagrams) {
            const startFig = figureForTable(d, p.ownerTableId);
            const endFig = figureForTable(d, p.refTableId);
            if (!startFig || !endFig) {
                log.push(`warning: ${p.fkName} not drawn on ${childText(d, 'name')} (endpoint table not placed there)`);
                continue;
            }
            const conn = buildConnection(ctx.mint, {
                fkId: p.fkId, fkName: p.fkName,
                startFigureId: attr(startFig, 'id'), endFigureId: attr(endFig, 'id'),
                diagramId: attr(d, 'id'),
            });
            child(d, 'connections').kids.push(conn);
            touch(d);
            drew++;
            log.push(`drew ${p.fkName} on ${childText(d, 'name')}`);
        }
        if (!drew) log.push(`warning: ${p.fkName} has no diagram connection (endpoints not co-placed)`);
    }
    ctx.pending.length = 0;
}

function addTableOp(ctx, spec, log) {
    if (!spec.name) fail('addTables: table name required');
    if (tableByName(ctx.schema, spec.name)) fail(`table ${spec.name} already exists`);
    const table = buildTable(ctx.mint, spec, attr(ctx.schema, 'id'));
    child(ctx.schema, 'tables').kids.push(table);
    touch(ctx.schema);
    log.push(`added table ${spec.name} (${(spec.columns || []).length} columns)`);
    for (const fkSpec of spec.foreignKeys || []) {
        addForeignKeyOp(ctx, table, { onDelete: 'NO ACTION', onUpdate: 'NO ACTION', ...fkSpec }, log);
    }
    if (spec.diagram) {
        const created = [];
        const { diagram } = ensureDiagram(ctx, spec.diagram, created);
        for (const c of created) log.push(`created diagram ${c}`);
        placeFigure(ctx, diagram, table, spec, log);
    }
    return table;
}

// ---------------------------------------------------------------------------
// model load/save
// ---------------------------------------------------------------------------

function loadModel(mwbPath) {
    const raw = readFileSync(mwbPath);
    const zip = readZip(raw);
    const docEntry = zip.entries.find((e) => e.name === 'document.mwb.xml');
    if (!docEntry) fail(`${mwbPath}: document.mwb.xml not found in archive`);
    const lockEntry = zip.entries.find((e) => e.name === 'lock');
    const { decl, root } = parseXml(docEntry.data.toString('utf8'));
    const mint = new PtrMint(root);
    const schema = findSchema(root);
    const physModel = findPhysicalModel(root);
    return { raw, zip, decl, root, mint, schema, physModel, lockEntry, pending: [] };
}

function saveModel(ctx, outPath) {
    const xml = serializeXml(ctx.decl, ctx.root);
    const { time, date } = dosDateTime(new Date());
    const entries = [{ name: 'lock', method: 0, time, date, attrs: (0o100600 * 0x10000) >>> 0, data: ctx.lockEntry ? ctx.lockEntry.data : Buffer.from('99033\0', 'binary') }];
    entries.push({ name: 'document.mwb.xml', method: 8, time, date, attrs: (0o100644 * 0x10000) >>> 0, data: Buffer.from(xml, 'utf8') });
    const origComment = ctx.zip.comment.length ? ctx.zip.comment : Buffer.from('MySQL Workbench Model archive 1.0', 'utf8');
    writeFileSync(outPath, writeZip(entries, origComment));
}

// ---------------------------------------------------------------------------
// digest
// ---------------------------------------------------------------------------

function digestModel(ctx) {
    const tables = tablesOf(ctx.schema).map((t) => {
        const pkLink = child(t, 'primaryKey');
        const pkId = pkLink ? pkLink.text : null;
        const pkIdx = pkId ? ctx.ids.get(pkId) : null;
        const pkCols = pkIdx
            ? children(pkIdx, 'columns').map((ic) => {
                const rc = child(ic, 'referencedColumn');
                const col = rc ? ctx.ids.get(rc.text) : null;
                return col ? childText(col, 'name') : '?';
            })
            : [];
        return {
            name: childText(t, 'name'),
            comment: childText(t, 'comment') || '',
            engine: childText(t, 'tableEngine') || '',
            columns: colsOf(t).map((c) => ({
                name: childText(c, 'name'),
                type: displayType(c),
                notNull: childText(c, 'isNotNull') === '1',
                autoIncrement: childText(c, 'autoIncrement') === '1',
                default: childText(c, 'defaultValue') || null,
                comment: childText(c, 'comment') || '',
                pk: pkCols.includes(childText(c, 'name')),
            })),
            primaryKey: pkCols,
            indexes: children(t, 'indices').map((ix) => ({
                name: childText(ix, 'name'),
                type: childText(ix, 'indexType'),
                unique: childText(ix, 'unique') === '1',
                columns: children(ix, 'columns').map((ic) => {
                    const rc = child(ic, 'referencedColumn');
                    const col = rc ? ctx.ids.get(rc.text) : null;
                    return col ? childText(col, 'name') : '?';
                }),
            })),
            foreignKeys: children(t, 'foreignKeys').map((fk) => {
                const rt = child(fk, 'referencedTable');
                const refTable = rt && !isExternalRef(rt.text) ? ctx.ids.get(rt.text) : null;
                const cols = children(fk, 'columns').map((l) => {
                    const col = ctx.ids.get(l.text);
                    return col ? childText(col, 'name') : '?';
                });
                const refCols = children(fk, 'referencedColumns').map((l) => {
                    const col = ctx.ids.get(l.text);
                    return col ? childText(col, 'name') : '?';
                });
                return {
                    name: childText(fk, 'name'),
                    columns: cols,
                    refTable: refTable ? childText(refTable, 'name') : '?',
                    refColumns: refCols,
                    onDelete: childText(fk, 'deleteRule'),
                    onUpdate: childText(fk, 'updateRule'),
                };
            }),
            diagrams: diagramsOf(ctx.physModel)
                .filter((d) => figureForTable(d, attr(t, 'id')))
                .map((d) => childText(d, 'name')),
        };
    });
    return {
        schema: childText(ctx.schema, 'name'),
        tables,
        diagrams: diagramsOf(ctx.physModel).map((d) => ({
            name: childText(d, 'name'),
            figures: figuresOf(d).map((f) => {
                const tl = child(f, 'table');
                const table = tl ? ctx.ids.get(tl.text) : null;
                return table ? childText(table, 'name') : '?';
            }),
            connections: children(d, 'connections').map((c) => {
                const fl = child(c, 'foreignKey');
                const fk = fl && !isExternalRef(fl.text) ? ctx.ids.get(fl.text) : null;
                return fk ? childText(fk, 'name') : '?';
            }),
        })),
    };
}

function printDigestText(d) {
    const lines = [];
    lines.push(`Schema: ${d.schema} — ${d.tables.length} tables`);
    lines.push(`Diagrams (${d.diagrams.length}): ${d.diagrams.map((x) => `${x.name} [${x.figures.length} figs, ${x.connections.length} conns]`).join(' | ')}`);
    lines.push('');
    for (const t of d.tables) {
        lines.push(`TABLE ${t.name}${t.engine ? ` (engine=${t.engine})` : ''}${t.comment ? ` — ${t.comment}` : ''}`);
        for (const c of t.columns) {
            const flags = [c.pk ? 'PK' : null, c.notNull ? 'NN' : null, c.autoIncrement ? 'AI' : null].filter(Boolean).join(',');
            lines.push(`  ${c.name} ${c.type}${flags ? ` [${flags}]` : ''}${c.default !== null ? ` DEFAULT ${c.default}` : ''}${c.comment ? ` — ${c.comment}` : ''}`);
        }
        for (const ix of t.indexes) {
            if (ix.type === 'PRIMARY') continue;
            lines.push(`  INDEX ${ix.name} (${ix.columns.join(', ')})${ix.unique ? ' UNIQUE' : ''}`);
        }
        for (const fk of t.foreignKeys) {
            lines.push(`  FK ${fk.name} (${fk.columns.join(', ')}) -> ${fk.refTable}(${fk.refColumns.join(', ')}) [${fk.onDelete}/${fk.onUpdate}]`);
        }
        lines.push(`  on diagrams: ${t.diagrams.join(', ') || '(none)'}`);
        lines.push('');
    }
    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// apply
// ---------------------------------------------------------------------------

function applySpec(ctx, spec, log) {
    const createdDiagrams = [];
    for (const r of spec.renameTables || []) {
        const t = tableByName(ctx.schema, r.from);
        if (!t) fail(`renameTables: ${r.from} not found`);
        if (tableByName(ctx.schema, r.to)) fail(`renameTables: ${r.to} already exists`);
        child(t, 'name').text = r.to;
        child(t, 'oldName').text = r.from;
        touch(t);
        // figures carry the table name too
        for (const d of diagramsOf(ctx.physModel)) {
            const f = figureForTable(d, attr(t, 'id'));
            if (f) { child(f, 'name').text = r.to; touch(f); }
        }
        log.push(`renamed table ${r.from} -> ${r.to}`);
    }
    for (const r of spec.renameColumns || []) {
        const t = tableByName(ctx.schema, r.table);
        if (!t) fail(`renameColumns: table ${r.table} not found`);
        const c = colByName(t, r.from);
        if (!c) fail(`renameColumns: ${r.table}.${r.from} not found`);
        if (colByName(t, r.to)) fail(`renameColumns: ${r.table}.${r.to} already exists`);
        child(c, 'name').text = r.to;
        child(c, 'oldName').text = r.from;
        touch(c); touch(t);
        log.push(`renamed column ${r.table}.${r.from} -> ${r.to}`);
    }
    for (const d of spec.createDiagrams || []) {
        if (!d.name) fail('createDiagrams: name required');
        const r = ensureDiagram(ctx, d.name, createdDiagrams);
        if (r.created) log.push(`created diagram ${d.name}`);
        else log.push(`diagram ${d.name} already exists`);
    }
    for (const t of spec.addTables || []) {
        // addTableOp auto-creates a named-but-missing diagram (per project convention)
        addTableOp(ctx, t, log);
    }
    for (const a of spec.addColumns || []) {
        const t = tableByName(ctx.schema, a.table);
        if (!t) fail(`addColumns: table ${a.table} not found`);
        const colsEl = child(t, 'columns');
        for (const c of a.columns || []) {
            if (colByName(t, c.name)) fail(`addColumns: ${a.table}.${c.name} already exists`);
            colsEl.kids.push(buildColumn(ctx.mint, c, attr(t, 'id')));
            log.push(`added column ${a.table}.${c.name}`);
        }
        touch(t);
    }
    for (const p of spec.placeTables || []) {
        const t = tableByName(ctx.schema, p.table);
        if (!t) fail(`placeTables: table ${p.table} not found`);
        let d = diagramByName(ctx.physModel, p.diagram);
        if (!d) {
            const created = [];
            d = ensureDiagram(ctx, p.diagram, created).diagram;
            for (const c of created) log.push(`created diagram ${c}`);
        }
        placeFigure(ctx, d, t, p, log);
    }
    for (const f of spec.addForeignKeys || []) {
        const t = tableByName(ctx.schema, f.table);
        if (!t) fail(`addForeignKeys: table ${f.table} not found`);
        addForeignKeyOp(ctx, t, { onDelete: 'NO ACTION', onUpdate: 'NO ACTION', ...f }, log);
    }
    drawPendingConnections(ctx, log);
}

// ---------------------------------------------------------------------------
// commands
// ---------------------------------------------------------------------------

function cmdDigest(args) {
    if (!args.mwb) fail('digest: --mwb <file.mwb> required');
    const ctx = loadModel(args.mwb);
    ctx.ids = idMap(ctx.root);
    const d = digestModel(ctx);
    const text = args.json ? JSON.stringify(d, null, 2) : printDigestText(d);
    if (args.out) writeFileSync(args.out, text + '\n');
    else process.stdout.write(text + (args.json ? '\n' : '\n'));
}

function cmdApply(args) {
    if (!args.mwb) fail('apply: --mwb <in.mwb> required');
    if (!args.spec) fail('apply: --spec <edits.json> required');
    if (!args.out && !args['dry-run']) fail('apply: --out <out.mwb> required (or --dry-run)');
    let spec;
    try {
        spec = JSON.parse(readFileSync(args.spec, 'utf8'));
    } catch (e) {
        fail(`cannot read spec: ${e.message}`);
    }
    const ctx = loadModel(args.mwb);
    ctx.ids = idMap(ctx.root);
    const log = [];
    applySpec(ctx, spec, log);
    for (const l of log) info(l);
    if (args['dry-run']) {
        info('dry run: no changes written');
        return;
    }
    saveModel(ctx, args.out);
    info(`wrote ${args.out}`);
    info('open the result in MySQL Workbench to confirm, then save to refresh checksums/cache');
}

function cmdRoundtrip(args) {
    if (!args.mwb) fail('roundtrip: --mwb <in.mwb> required');
    if (!args.out) fail('roundtrip: --out <out.mwb> required');
    const ctx = loadModel(args.mwb);
    saveModel(ctx, args.out);
    info(`wrote ${args.out} (parse + serialize, no edits)`);
}

function wbStructuralCheck(ctx) {
    const errors = [];
    const ids = idMap(ctx.root);
    const ptrs = new Set();
    const walk = (n) => {
        const p = attr(n, '_ptr_');
        if (p) {
            if (ptrs.has(p)) errors.push(`duplicate _ptr_ ${p}`);
            ptrs.add(p);
        }
        for (const k of n.kids) walk(k);
    };
    walk(ctx.root);
    const checkLink = (node, where) => {
        for (const k of node.kids) {
            if (k.tag === 'link' && k.text && !isExternalRef(k.text)) {
                if (!ids.has(k.text)) errors.push(`${where}: dangling link ${attr(k, 'key')} -> ${k.text}`);
            }
            checkLink(k, where);
        }
    };
    checkLink(ctx.root, 'model');
    // GRT value-type consistency: for each struct-name, every occurrence of a
    // key must share the same `type` attribute (GRT structs are fixed). A lone
    // outlier means this tool emitted the wrong type — Workbench then refuses
    // to unserialize the whole model ("expected type X, but got Y").
    const typeByStructKey = new Map();
    const walkObjs = (n) => {
        const sn = attr(n, 'struct-name');
        if (sn) {
            for (const k of n.kids) {
                if (k.tag === 'value' && attr(k, 'key') && attr(k, 'type')) {
                    const mkey = `${sn}\u0000${attr(k, 'key')}`;
                    const types = typeByStructKey.get(mkey) || (typeByStructKey.set(mkey, new Map()), typeByStructKey.get(mkey));
                    types.set(attr(k, 'type'), (types.get(attr(k, 'type')) || 0) + 1);
                }
            }
        }
        for (const k of n.kids) walkObjs(k);
    };
    walkObjs(ctx.root);
    const counts = (sn, key) => typeByStructKey.get(`${sn}\u0000${key}`) || new Map();
    const checkTypes = (n) => {
        const sn = attr(n, 'struct-name');
        if (sn) {
            const idsHere = attr(n, 'id');
            for (const k of n.kids) {
                if (k.tag === 'value' && attr(k, 'key') && attr(k, 'type')) {
                    const c = counts(sn, attr(k, 'key'));
                    const total = [...c.values()].reduce((a, b) => a + b, 0);
                    if (total > 1) {
                        const expected = [...c.entries()].sort((a, b) => b[1] - a[1])[0][0];
                        if (attr(k, 'type') !== expected) {
                            errors.push(`${sn}${idsHere ? ` ${idsHere}` : ''}: value "${attr(k, 'key')}" is type ${attr(k, 'type')}, expected ${expected}`);
                        }
                    }
                }
            }
        }
        for (const k of n.kids) checkTypes(k);
    };
    checkTypes(ctx.root);
    // FK integrity
    for (const t of tablesOf(ctx.schema)) {
        for (const fk of children(t, 'foreignKeys')) {
            const rt = child(fk, 'referencedTable');
            if (rt && !ids.has(rt.text)) errors.push(`FK ${childText(fk, 'name')}: unknown referencedTable`);
            for (const l of [...children(fk, 'columns'), ...children(fk, 'referencedColumns')]) {
                if (!ids.has(l.text)) errors.push(`FK ${childText(fk, 'name')}: unknown column ref`);
            }
            const ix = child(fk, 'index');
            if (ix && !ids.has(ix.text)) errors.push(`FK ${childText(fk, 'name')}: unknown backing index`);
        }
    }
    return errors;
}

// Workbench cannot expose the open model to startup scripts
// (grt.root.wb.doc stays None), so validation is log-based: open the model
// in Workbench and fail on loader error signatures. A corrupt model emits
// [ERR]/LibXml lines; a healthy one only emits benign Gtk noise.
const WB_ERROR_PATTERNS = [/\[ERR\]/, /LibXml\s*:\s*error/i, /Error loading/i, /failed to load/i];

function runWorkbenchValidation(mwbPath) {
    // Never open the user's file directly: validate a temp copy instead.
    const tmp = mkdtempSync(join(tmpdir(), 'wbcheck-'));
    const copy = join(tmp, 'check.mwb');
    copyFileSync(mwbPath, copy);
    // NOTE: --quit-when-done does not quit without --run-script, and --model
    // is ignored when combined with --run-script, so run bare under `timeout`
    // and scan the loader log. A healthy open attempts the model
    // ("open type: model") and emits no loader errors.
    const r = spawnSync('timeout', ['100', 'mysql-workbench',
        '--configdir', tmp, '--model', copy,
        '--log-to-stderr', '--log-level=debug1'],
        { encoding: 'utf8' });
    if (r.error) {
        return { ok: false, error: `workbench did not run: ${r.error.message}` };
    }
    const text = (r.stderr || '');
    if (!text.includes('open type: model')) {
        return { ok: false, error: 'workbench log shows no model open attempt', raw: text.slice(-1500) };
    }
    const hits = text.split('\n').filter((l) => !l.includes('Gtk-') && WB_ERROR_PATTERNS.some((p) => p.test(l)));
    if (hits.length) {
        return { ok: false, error: `Workbench reported ${hits.length} loader error(s)`, raw: hits.slice(0, 10).join('\n') };
    }
    return { ok: true };
}

function cmdWbcheck(args) {
    if (!args.mwb) fail('wbcheck: --mwb <file.mwb> required');
    const ctx = loadModel(args.mwb);
    const errors = wbStructuralCheck(ctx);
    if (errors.length) {
        for (const e of errors) process.stderr.write(`mwb-edit: structural: ${e}\n`);
        fail(`structural check failed (${errors.length} problem(s))`);
    }
    info('structural check passed');
    if (args.wb) {
        info('opening in MySQL Workbench for validation...');
        const v = runWorkbenchValidation(args.mwb);
        if (!v.ok) fail(`Workbench validation failed: ${v.error || 'unknown'}${v.raw ? '\n' + v.raw : ''}`);
        ctx.ids = idMap(ctx.root);
        const d = digestModel(ctx);
        info(`Workbench loaded the model cleanly: schema=${d.schema}, tables=${d.tables.length}, diagrams=${d.diagrams.length}`);
    }
}

function main() {
    const args = parseArgs(process.argv.slice(2));
    const cmd = args._[0];
    try {
        if (cmd === 'digest') cmdDigest(args);
        else if (cmd === 'apply') cmdApply(args);
        else if (cmd === 'roundtrip') cmdRoundtrip(args);
        else if (cmd === 'wbcheck') cmdWbcheck(args);
        else fail('usage: mwb-edit.mjs {digest|apply|roundtrip|wbcheck} [--mwb ..] ...');
    } catch (e) {
        if (e.code === 'ENOENT') fail(e.message);
        throw e;
    }
}

main();
